### ISSUE TITLE
background calibration fails if zbins_use.size <= 1

### ISSUE THREAD

**Issue by jacobic** [erykoff/redmapper#34]
Hi Eli,

Some quick feedback regarding the stability of the background calibration with multiple processes. I noticed 2 issues:

### Issue 1 occurs  if `zbins_use.size == 0`:

When `calib_nproc` (the number of processes specified by the number of cores on local machine for calibration), exceeds the number of redshift bins an IndexError is thrown. See config (converted to txt so it can be uploaded) and traceback:

RedMaPPer Config: [cal_sdss.yml.txt](https://github.com/erykoff/redmapper/files/3243819/cal_sdss.yml.txt)

```
Generating chisq background...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/u/jacobic/.local/anaconda3/envs/redmapper/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/u/jacobic/.local/anaconda3/envs/redmapper/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/u/jacobic/.local/anaconda3/envs/redmapper/lib/python3.7/site-packages/redmapper-0.2.5-py3.7-linux-x86_64.egg/redmapper/background.py", line 439, in _worker
    zrange_use = np.array([zbins_use[0], zbins_use[-1] + self.config.bkg_zbinsize])
IndexError: index 0 is out of bounds for axis 0 with size 0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/u/jacobic/.local/anaconda3/envs/redmapper/bin/redmapper_calibrate.py", line 4, in <module>
    __import__('pkg_resources').run_script('redmapper==0.2.5', 'redmapper_calibrate.py')
  File "/u/jacobic/.local/anaconda3/envs/redmapper/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/u/jacobic/.local/anaconda3/envs/redmapper/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/draco/u/jacobic/.local/anaconda3/envs/redmapper/lib/python3.7/site-packages/redmapper-0.2.5-py3.7-linux-x86_64.egg/EGG-INFO/scripts/redmapper_calibrate.py", line 19, in <module>
    calib.run()
  File "/u/jacobic/.local/anaconda3/envs/redmapper/lib/python3.7/site-packages/redmapper-0.2.5-py3.7-linux-x86_64.egg/redmapper/calibration/calibrate.py", line 111, in run
    calib_iteration.run(iteration)
  File "/u/jacobic/.local/anaconda3/envs/redmapper/lib/python3.7/site-packages/redmapper-0.2.5-py3.7-linux-x86_64.egg/redmapper/calibration/calibrate.py", line 362, in run
    bkg_gen.run()
  File "/u/jacobic/.local/anaconda3/envs/redmapper/lib/python3.7/site-packages/redmapper-0.2.5-py3.7-linux-x86_64.egg/redmapper/background.py", line 366, in run
    retvals = pool.map(self._worker, worker_list, chunksize=1)
  File "/u/jacobic/.local/anaconda3/envs/redmapper/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/u/jacobic/.local/anaconda3/envs/redmapper/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: index 0 is out of bounds for axis 0 with size 0
```

This makes complete sense since you try to distribute the redshift bins across as evenly as possible across the available workers. 

In most cases a user is likely to have more redshift bins than calibration processes. However, in the case that you specify more processes than redshift bins, the background calculation fails. 

I was just wondering if one or more of the following suggestions could be implemented in `redmapper/background.py` to improve stability and prevent other users experiencing this issue:

- If `calib_nproc` > `nzbins` then `calib_nproc` =  `nzbins`.
- Filter out  the worker-list if they contain only `False` values with `worker_list = [_ for _ in worker_list if any(_)]`
- Provide the user with a warning if they have set it to a value that is higher than what is required.
- Alternatively raise an exception stating that the user needs to modify `calib_nproc`.

I suggest the second bullet point because I notice that in some cases the load balancing across the processes is not always even (see screenshot below), some processes get 2 redshift bins while at the same time the first index of the worker-list sometimes gets 0 and the rest get 1 each. However, if any get 0 redshift bins an `IndexError` will be thrown.

<img width="1024" alt="Screenshot 2019-06-01 at 14 14 41" src="https://user-images.githubusercontent.com/9905226/58749272-4cc46680-8484-11e9-81b6-c69997a172b4.png">

## Issue 2 occurs if `zbins_use.size == 1`:

Even if the worker-list is filtered to avoid an `IndexError` being thrown, additional problems can still occur within `_worker(self, zbinmark)` if zlimmag is a scalar value (as it cannot be indexed) `zlimmag[bad] = self.config.limmag_catalog - 0.01` throws an exception. See screenshot below of variables in frame that causes the issue:

<img width="1439" alt="Screenshot 2019-06-01 at 15 41 25" src="https://user-images.githubusercontent.com/9905226/58749270-446c2b80-8484-11e9-8083-382a64b2902e.png">

This could be avoided by checking `if isistance(zlimmag, np.float)` then `zlimmag = np.array([zlimmag])` to allow it to be indexed.

Ultimately these errors occur due to the user sub optimally specifying 3 things. The redshift range specified, the background calibration redshift binsize and the number of processes requested. 

Please let me know if you have any questions, comments or advice.

Cheers,
Jacob

**Comment by erykoff** [comment]
Thank you for the report!  I'm working on other things at the same time, but these will be fixed soon. The solution in the second case is to use `np.atleast_1d()`.
