### ISSUE TITLE
encounter error when install fitsio

### ISSUE THREAD

**Issue by stanaclara** [erykoff/redmapper#37]
Thanks for your package.
I encounter an error when I install fitsio. I have tried different version of fitsio. But this error still appear.
` Running setup.py install for fitsio ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\dell\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-5bnd753m\\fitsio\\setup.py'"'"'; __file__='"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-5bnd753m\\fitsio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\DELL\AppData\Local\Temp\pip-record-xz9iauv3\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\DELL\AppData\Local\Temp\pip-install-5bnd753m\fitsio\
    Complete output (54 lines):
    c:\users\dell\appdata\local\programs\python\python37-32\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\fitsio
    copying fitsio\fitslib.py -> build\lib.win32-3.7\fitsio
    copying fitsio\header.py -> build\lib.win32-3.7\fitsio
    copying fitsio\test.py -> build\lib.win32-3.7\fitsio
    copying fitsio\util.py -> build\lib.win32-3.7\fitsio
    copying fitsio\__init__.py -> build\lib.win32-3.7\fitsio
    creating build\lib.win32-3.7\fitsio\hdu
    copying fitsio\hdu\base.py -> build\lib.win32-3.7\fitsio\hdu
    copying fitsio\hdu\image.py -> build\lib.win32-3.7\fitsio\hdu
    copying fitsio\hdu\table.py -> build\lib.win32-3.7\fitsio\hdu
    copying fitsio\hdu\__init__.py -> build\lib.win32-3.7\fitsio\hdu
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\DELL\AppData\Local\Temp\pip-install-5bnd753m\fitsio\setup.py", line 289, in <module>
        cmdclass={"build_ext": build_ext_subclass}
      File "c:\users\dell\appdata\local\programs\python\python37-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\dell\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\dell\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\dell\appdata\local\programs\python\python37-32\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\dell\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\dell\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\dell\appdata\local\programs\python\python37-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\dell\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\dell\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\DELL\AppData\Local\Temp\pip-install-5bnd753m\fitsio\setup.py", line 72, in run
        build_ext.run(self)
      File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\build_ext.py", line 75, in run
        _build_ext.run(self)
      File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "c:\users\dell\appdata\local\programs\python\python37-32\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\DELL\AppData\Local\Temp\pip-install-5bnd753m\fitsio\setup.py", line 84, in build_extensions
        CCold = self.compiler.compiler
    AttributeError: 'MSVCCompiler' object has no attribute 'compiler'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\dell\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-5bnd753m\\fitsio\\setup.py'"'"'; __file__='"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-5bnd753m\\fitsio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\DELL\AppData\Local\Temp\pip-record-xz9iauv3\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.`

**Comment by erykoff** [comment]
Thank you for your feedback.  First of all, this is not an issue for redmapper, this is an issue for fitsio.  Second of all, neither fitsio nor redmapper has ever been tested under windows, and that is not a supported environment.
